### ISSUE TITLE
panic when using --single flag

### ISSUE THREAD

**Issue by dch** [algesten/rabbiteer-rs#6]
I 😍 this super handy tool so much -- thanks!

I'm seeing a panic only when using the ``-single` flag, running on FreeBSD:

```
$ env RUST_BACKTRACE=1 rabbiteer -U $BROKER subscribe --exchange amq.direct --queue api.search --single --noack

{"data":{...},"meta":{"reply_to":"api.search.reply.11bc98c338bd1858"}}

thread 'main' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: amqp::channel::Channel::read
  11: amqp::channel::Channel::close
  12: rabbiteer::subscribe::do_subscribe::{{closure}}
  13: <rabbiteer::client::Receiver as amqp::channel::Consumer>::handle_delivery
  14: amqp::channel::Channel::read
  15: amqp::channel::Channel::start_consuming
  16: rabbiteer::subscribe::do_subscribe
  17: rabbiteer::_main
  18: rabbiteer::main
  19: std::rt::lang_start::{{closure}}
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:101
  22: std::rt::lang_start_internal
  23: main
  24: _start
             at /usr/src/lib/csu/amd64/crt1.c:74
```

## compiler & OS

```
$ rabbiteer --version
Rabbiteer 1.4.0
$ rustc --version
rustc 1.24.0
$ uname -a
FreeBSD wintermute 12.0-CURRENT FreeBSD 12.0-CURRENT #2 r330131+c2b4c41f8e15(master): Wed Feb 28 22:36:38 UTC 2018     root@wintermute:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd664
```

As I've not reported bugs in rust code before please let me know if there's anything more helpful I can provide.

**Comment by dch** [comment]
FWIW I re-tried this using master and not 1.4.0 from crates, and same stacktrace

**Comment by dch** [comment]
I read a bit more of the code, I understand that this is effectively making an easy exit, but perhaps we could catch this specific error and then return cleanly to the user. Would you take a PR for that?

**Comment by dch** [comment]
https://github.com/skunkwerks/rabbiteer/commit/41290ce1731cf0093cc5e67851e4c6c1cf79a47a this catches all errors, it's a step in the right direction. perhaps using https://doc.rust-lang.org/std/panic/fn.catch_unwind.html in `src/libcore/results.rs` directly would be a better solution?
